name: Build

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - name: Get versions
        run: |
          echo "VTS_VERSION=$(grep -oP '^ARG NGINX_VTS_VERSION="\K[^"]*' Containerfile)" >> $GITHUB_ENV
          echo "NGINX_VERSION=$(grep -oP '^ARG NGINX_VERSION="\K[^"]*' Containerfile)" >> $GITHUB_ENV
      - uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Containerfile
          push: false
          tags: test:nginx-${{ env.NGINX_VERSION }}-vts-${{ env.VTS_VERSION }}
