name: Publish

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * 1'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Get versions
        run: |
          echo "VTS_VERSION=$(grep -oP '^ARG VTS_VERSION=\K.*' Containerfile)" >> $GITHUB_ENV
          echo "NGINX_VERSION=$(grep -oP '^ARG NGINX_VERSION=\K.*' Containerfile)" >> $GITHUB_ENV
      - uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Containerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:nginx-${{ env.NGINX_VERSION }}-vts-${{ env.VTS_VERSION }}
          labels: |
            org.opencontainers.image.source=${{ github.repositoryUrl }}
            org.opencontainers.image.version=${{ env.NGINX_VERSION }}-${{ env.VTS_VERSION }}
